# Generated by Django 5.1.2 on 2025-01-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image_file',
            field=models.ImageField(upload_to='static/img/logo/', verbose_name='Logo'),
        ),
    ]
