# Generated by Django 5.1.2 on 2025-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_logo_svg_file_alter_logo_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/img/logo/', verbose_name='Bilddatei'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='media/static/svg/logo/', verbose_name='Vektorgrafik'),
        ),
    ]
