# Generated by Django 5.1.5 on 2025-03-13 14:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_logo_image_file_alter_logo_svg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(max_length=100000, verbose_name='Datenschutzerklärung')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(max_length=100000, verbose_name='Datenschutzerklärung')),
            ],
        ),
    ]
