# Generated by Django 5.2.4 on 2025-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_imprint_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/logo/', verbose_name='Bilddatei'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='static/svg/logo/', verbose_name='Vektorgrafik'),
        ),
    ]
