# Generated by Django 5.2.4 on 2025-07-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_logo_image_file_alter_logo_svg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Bilddatei'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Vektorgrafik'),
        ),
    ]
