# Generated by Django 5.1.5 on 2025-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_content_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_article',
            field=models.BooleanField(default=False),
        ),
    ]
