# Generated by Django 5.1.5 on 2025-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articletemplate_alter_article_category_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
    ]
