# Generated by Django 5.2.4 on 2025-07-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_category_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_article',
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images', verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bildunterschrift')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Artikel')),
            ],
        ),
    ]
