# Generated by Django 5.2.4 on 2025-07-21 12:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articleimage_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='Inhalt'),
        ),
    ]
