# Generated by Django 5.1.2 on 2025-01-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_draft_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
