# Generated by Django 5.1.5 on 2025-03-13 09:29

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_article_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(max_length=2048, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Entwurf'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='öffentlich'),
        ),
        migrations.AlterField(
            model_name='news',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
