# Generated by Django 5.1.5 on 2025-03-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_content_alter_news_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Name')),
                ('template', models.CharField(max_length=128, verbose_name='TemplateDirectory')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newstemplate', verbose_name='Design'),
        ),
    ]
