# Generated by Django 5.1.2 on 2025-01-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_indexheader_indextext_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image_file',
            field=models.ImageField(upload_to='teaser/'),
        ),
    ]
