# Generated by Django 5.1.2 on 2025-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_teaser_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaserIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('svg', models.FileField(upload_to='teaser/icons')),
            ],
        ),
        migrations.AlterField(
            model_name='teaser',
            name='image_file',
            field=models.ImageField(upload_to='teaser/images/'),
        ),
    ]
