# Generated by Django 5.1.2 on 2025-01-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_teasericon_alter_teaser_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image_file',
            field=models.ImageField(upload_to='media/teaser/images/'),
        ),
        migrations.AlterField(
            model_name='teasericon',
            name='svg',
            field=models.FileField(upload_to='media/teaser/icons'),
        ),
    ]
