# Generated by Django 5.1.5 on 2025-02-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_indexcard_delete_indextext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='content',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
