# Generated by Django 5.1.5 on 2025-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_content_category_remove_content_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='image_file',
            field=models.ImageField(upload_to='media/teaser/images/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='text',
            field=models.CharField(max_length=64, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='teasericon',
            name='svg',
            field=models.FileField(upload_to='media/teaser/icons', verbose_name='svg_datei'),
        ),
        migrations.AlterField(
            model_name='teasericon',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Titel'),
        ),
    ]
