# Generated by Django 5.2.4 on 2025-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_teaser_description_alter_teaser_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image_file',
            field=models.ImageField(upload_to='teaser/images/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='teasericon',
            name='svg',
            field=models.FileField(upload_to='teaser/icons', verbose_name='svg_datei'),
        ),
    ]
